### ISSUE TITLE
Redo location map for sim to yaml file

### ISSUE THREAD

**Issue by thejosmeister** [thejosmeister/SimsigTtTools#20]
Want a more forgiving map of locations

Will look like:

```
Entry_points:
  EUPOX: 
    readable_names: aaaa, aaaa, sdsda
    asssoc_sim_location: ABCDE
...
Locations:
  SDON: Swindon, Swindon [SWI]
...
```
